/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 105
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 87
#define ALIAS_COUNT 0
#define TOKEN_COUNT 47
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_blueprint = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_EQ = 5,
  anon_sym_version = 6,
  anon_sym_name = 7,
  anon_sym_description = 8,
  anon_sym_author = 9,
  anon_sym_min_achitek_version = 10,
  anon_sym_prompt = 11,
  anon_sym_type = 12,
  anon_sym_help = 13,
  anon_sym_choices = 14,
  anon_sym_default = 15,
  anon_sym_required = 16,
  anon_sym_depends_on = 17,
  anon_sym_string = 18,
  anon_sym_paragraph = 19,
  anon_sym_bool = 20,
  anon_sym_select = 21,
  anon_sym_multiselect = 22,
  anon_sym_validate = 23,
  anon_sym_regex = 24,
  anon_sym_min_length = 25,
  anon_sym_max_length = 26,
  anon_sym_min_selections = 27,
  anon_sym_max_selections = 28,
  anon_sym_EQ_EQ = 29,
  anon_sym_BANG_EQ = 30,
  anon_sym_DOT = 31,
  anon_sym_LPAREN = 32,
  anon_sym_RPAREN = 33,
  sym_method_name = 34,
  anon_sym_all = 35,
  anon_sym_any = 36,
  anon_sym_COMMA = 37,
  anon_sym_LBRACK = 38,
  anon_sym_RBRACK = 39,
  anon_sym_DQUOTE = 40,
  aux_sym_string_literal_token1 = 41,
  sym_escape_sequence = 42,
  sym_integer = 43,
  anon_sym_true = 44,
  anon_sym_false = 45,
  sym_comment = 46,
  sym_file = 47,
  sym_blueprint_block = 48,
  sym_blueprint_attribute = 49,
  sym_blueprint_attribute_key = 50,
  sym_prompt_block = 51,
  sym_question_attribute = 52,
  sym_type_attribute = 53,
  sym_help_attribute = 54,
  sym_choices_attribute = 55,
  sym_default_attribute = 56,
  sym_required_attribute = 57,
  sym_depends_on_attribute = 58,
  sym_question_type = 59,
  sym_validate_block = 60,
  sym_validate_attribute = 61,
  sym_regex_attribute = 62,
  sym_min_length_attribute = 63,
  sym_max_length_attribute = 64,
  sym_min_selections_attribute = 65,
  sym_max_selections_attribute = 66,
  sym_dependency_expr = 67,
  sym_simple_dependency = 68,
  sym_comparison_dependency = 69,
  sym_method_call_dependency = 70,
  sym_combinator_dependency = 71,
  sym_combinator_name = 72,
  sym_dependency_list = 73,
  sym_value = 74,
  sym_literal_value = 75,
  sym_array = 76,
  sym_value_list = 77,
  sym_string_literal = 78,
  sym_boolean = 79,
  aux_sym_file_repeat1 = 80,
  aux_sym_blueprint_block_repeat1 = 81,
  aux_sym_prompt_block_repeat1 = 82,
  aux_sym_validate_block_repeat1 = 83,
  aux_sym_dependency_list_repeat1 = 84,
  aux_sym_value_list_repeat1 = 85,
  aux_sym_string_literal_repeat1 = 86,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_blueprint] = "blueprint",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_version] = "version",
  [anon_sym_name] = "name",
  [anon_sym_description] = "description",
  [anon_sym_author] = "author",
  [anon_sym_min_achitek_version] = "min_achitek_version",
  [anon_sym_prompt] = "prompt",
  [anon_sym_type] = "type",
  [anon_sym_help] = "help",
  [anon_sym_choices] = "choices",
  [anon_sym_default] = "default",
  [anon_sym_required] = "required",
  [anon_sym_depends_on] = "depends_on",
  [anon_sym_string] = "string",
  [anon_sym_paragraph] = "paragraph",
  [anon_sym_bool] = "bool",
  [anon_sym_select] = "select",
  [anon_sym_multiselect] = "multiselect",
  [anon_sym_validate] = "validate",
  [anon_sym_regex] = "regex",
  [anon_sym_min_length] = "min_length",
  [anon_sym_max_length] = "max_length",
  [anon_sym_min_selections] = "min_selections",
  [anon_sym_max_selections] = "max_selections",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_method_name] = "method_name",
  [anon_sym_all] = "all",
  [anon_sym_any] = "any",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_comment] = "comment",
  [sym_file] = "file",
  [sym_blueprint_block] = "blueprint_block",
  [sym_blueprint_attribute] = "blueprint_attribute",
  [sym_blueprint_attribute_key] = "blueprint_attribute_key",
  [sym_prompt_block] = "prompt_block",
  [sym_question_attribute] = "question_attribute",
  [sym_type_attribute] = "type_attribute",
  [sym_help_attribute] = "help_attribute",
  [sym_choices_attribute] = "choices_attribute",
  [sym_default_attribute] = "default_attribute",
  [sym_required_attribute] = "required_attribute",
  [sym_depends_on_attribute] = "depends_on_attribute",
  [sym_question_type] = "question_type",
  [sym_validate_block] = "validate_block",
  [sym_validate_attribute] = "validate_attribute",
  [sym_regex_attribute] = "regex_attribute",
  [sym_min_length_attribute] = "min_length_attribute",
  [sym_max_length_attribute] = "max_length_attribute",
  [sym_min_selections_attribute] = "min_selections_attribute",
  [sym_max_selections_attribute] = "max_selections_attribute",
  [sym_dependency_expr] = "dependency_expr",
  [sym_simple_dependency] = "simple_dependency",
  [sym_comparison_dependency] = "comparison_dependency",
  [sym_method_call_dependency] = "method_call_dependency",
  [sym_combinator_dependency] = "combinator_dependency",
  [sym_combinator_name] = "combinator_name",
  [sym_dependency_list] = "dependency_list",
  [sym_value] = "value",
  [sym_literal_value] = "literal_value",
  [sym_array] = "array",
  [sym_value_list] = "value_list",
  [sym_string_literal] = "string_literal",
  [sym_boolean] = "boolean",
  [aux_sym_file_repeat1] = "file_repeat1",
  [aux_sym_blueprint_block_repeat1] = "blueprint_block_repeat1",
  [aux_sym_prompt_block_repeat1] = "prompt_block_repeat1",
  [aux_sym_validate_block_repeat1] = "validate_block_repeat1",
  [aux_sym_dependency_list_repeat1] = "dependency_list_repeat1",
  [aux_sym_value_list_repeat1] = "value_list_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_blueprint] = anon_sym_blueprint,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_version] = anon_sym_version,
  [anon_sym_name] = anon_sym_name,
  [anon_sym_description] = anon_sym_description,
  [anon_sym_author] = anon_sym_author,
  [anon_sym_min_achitek_version] = anon_sym_min_achitek_version,
  [anon_sym_prompt] = anon_sym_prompt,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_help] = anon_sym_help,
  [anon_sym_choices] = anon_sym_choices,
  [anon_sym_default] = anon_sym_default,
  [anon_sym_required] = anon_sym_required,
  [anon_sym_depends_on] = anon_sym_depends_on,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_paragraph] = anon_sym_paragraph,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_select] = anon_sym_select,
  [anon_sym_multiselect] = anon_sym_multiselect,
  [anon_sym_validate] = anon_sym_validate,
  [anon_sym_regex] = anon_sym_regex,
  [anon_sym_min_length] = anon_sym_min_length,
  [anon_sym_max_length] = anon_sym_max_length,
  [anon_sym_min_selections] = anon_sym_min_selections,
  [anon_sym_max_selections] = anon_sym_max_selections,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_method_name] = sym_method_name,
  [anon_sym_all] = anon_sym_all,
  [anon_sym_any] = anon_sym_any,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_comment] = sym_comment,
  [sym_file] = sym_file,
  [sym_blueprint_block] = sym_blueprint_block,
  [sym_blueprint_attribute] = sym_blueprint_attribute,
  [sym_blueprint_attribute_key] = sym_blueprint_attribute_key,
  [sym_prompt_block] = sym_prompt_block,
  [sym_question_attribute] = sym_question_attribute,
  [sym_type_attribute] = sym_type_attribute,
  [sym_help_attribute] = sym_help_attribute,
  [sym_choices_attribute] = sym_choices_attribute,
  [sym_default_attribute] = sym_default_attribute,
  [sym_required_attribute] = sym_required_attribute,
  [sym_depends_on_attribute] = sym_depends_on_attribute,
  [sym_question_type] = sym_question_type,
  [sym_validate_block] = sym_validate_block,
  [sym_validate_attribute] = sym_validate_attribute,
  [sym_regex_attribute] = sym_regex_attribute,
  [sym_min_length_attribute] = sym_min_length_attribute,
  [sym_max_length_attribute] = sym_max_length_attribute,
  [sym_min_selections_attribute] = sym_min_selections_attribute,
  [sym_max_selections_attribute] = sym_max_selections_attribute,
  [sym_dependency_expr] = sym_dependency_expr,
  [sym_simple_dependency] = sym_simple_dependency,
  [sym_comparison_dependency] = sym_comparison_dependency,
  [sym_method_call_dependency] = sym_method_call_dependency,
  [sym_combinator_dependency] = sym_combinator_dependency,
  [sym_combinator_name] = sym_combinator_name,
  [sym_dependency_list] = sym_dependency_list,
  [sym_value] = sym_value,
  [sym_literal_value] = sym_literal_value,
  [sym_array] = sym_array,
  [sym_value_list] = sym_value_list,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean] = sym_boolean,
  [aux_sym_file_repeat1] = aux_sym_file_repeat1,
  [aux_sym_blueprint_block_repeat1] = aux_sym_blueprint_block_repeat1,
  [aux_sym_prompt_block_repeat1] = aux_sym_prompt_block_repeat1,
  [aux_sym_validate_block_repeat1] = aux_sym_validate_block_repeat1,
  [aux_sym_dependency_list_repeat1] = aux_sym_dependency_list_repeat1,
  [aux_sym_value_list_repeat1] = aux_sym_value_list_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_blueprint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_version] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_name] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_description] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_author] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_min_achitek_version] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_prompt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_help] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_choices] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_default] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_required] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_depends_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_paragraph] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_select] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_multiselect] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_validate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_regex] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_min_length] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_max_length] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_min_selections] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_max_selections] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_method_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_all] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_any] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym_blueprint_block] = {
    .visible = true,
    .named = true,
  },
  [sym_blueprint_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_blueprint_attribute_key] = {
    .visible = true,
    .named = true,
  },
  [sym_prompt_block] = {
    .visible = true,
    .named = true,
  },
  [sym_question_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_type_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_help_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_choices_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_default_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_required_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_depends_on_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_question_type] = {
    .visible = true,
    .named = true,
  },
  [sym_validate_block] = {
    .visible = true,
    .named = true,
  },
  [sym_validate_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_regex_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_min_length_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_max_length_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_min_selections_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_max_selections_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_dependency_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_dependency] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_dependency] = {
    .visible = true,
    .named = true,
  },
  [sym_method_call_dependency] = {
    .visible = true,
    .named = true,
  },
  [sym_combinator_dependency] = {
    .visible = true,
    .named = true,
  },
  [sym_combinator_name] = {
    .visible = true,
    .named = true,
  },
  [sym_dependency_list] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_value] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_value_list] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_blueprint_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_prompt_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_validate_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dependency_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_arguments = 2,
  field_key = 3,
  field_left = 4,
  field_method = 5,
  field_name = 6,
  field_operator = 7,
  field_receiver = 8,
  field_reference = 9,
  field_right = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_arguments] = "arguments",
  [field_key] = "key",
  [field_left] = "left",
  [field_method] = "method",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_receiver] = "receiver",
  [field_reference] = "reference",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 3},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
  [2] =
    {field_name, 1},
  [3] =
    {field_value, 2},
  [4] =
    {field_reference, 0},
  [5] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [8] =
    {field_arguments, 2},
    {field_name, 0},
  [10] =
    {field_argument, 4},
    {field_method, 2},
    {field_receiver, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '!', 5,
        '"', 23,
        '#', 28,
        '(', 17,
        ')', 18,
        ',', 19,
        '.', 16,
        '=', 13,
        '[', 20,
        '\\', 7,
        ']', 21,
        '{', 10,
        '}', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '}') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '#') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '=') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(26);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '!', 5,
        '"', 23,
        '#', 28,
        '(', 17,
        ')', 18,
        ',', 19,
        '.', 16,
        '=', 13,
        '[', 20,
        ']', 21,
        '{', 10,
        '}', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'f', 5,
        'h', 6,
        'm', 7,
        'n', 8,
        'p', 9,
        'r', 10,
        's', 11,
        't', 12,
        'v', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(17);
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 'h') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == 'i') ADVANCE(25);
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(28);
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(33);
      if (lookahead == 'y') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 15:
      if (lookahead == 'y') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(40);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == 'p') ADVANCE(45);
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 24:
      if (lookahead == 'x') ADVANCE(49);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 27:
      if (lookahead == 'm') ADVANCE(52);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 30:
      if (lookahead == 'g') ADVANCE(55);
      if (lookahead == 'q') ADVANCE(56);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(57);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(59);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(60);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_all);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_any);
      END_STATE();
    case 39:
      if (lookahead == 'h') ADVANCE(63);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(65);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(66);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 44:
      if (lookahead == 'a') ADVANCE(68);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 46:
      if (lookahead == 'c') ADVANCE(70);
      END_STATE();
    case 47:
      if (lookahead == 's') ADVANCE(71);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(72);
      END_STATE();
    case 49:
      if (lookahead == '_') ADVANCE(73);
      END_STATE();
    case 50:
      if (lookahead == '_') ADVANCE(74);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 53:
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 54:
      if (lookahead == 'm') ADVANCE(78);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 56:
      if (lookahead == 'u') ADVANCE(80);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(82);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 61:
      if (lookahead == 'i') ADVANCE(85);
      END_STATE();
    case 62:
      if (lookahead == 's') ADVANCE(86);
      END_STATE();
    case 63:
      if (lookahead == 'o') ADVANCE(87);
      END_STATE();
    case 64:
      if (lookahead == 'p') ADVANCE(88);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 66:
      if (lookahead == 'c') ADVANCE(89);
      END_STATE();
    case 67:
      if (lookahead == 'a') ADVANCE(90);
      END_STATE();
    case 68:
      if (lookahead == 'u') ADVANCE(91);
      END_STATE();
    case 69:
      if (lookahead == 'n') ADVANCE(92);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_help);
      END_STATE();
    case 73:
      if (lookahead == 'l') ADVANCE(95);
      if (lookahead == 's') ADVANCE(96);
      END_STATE();
    case 74:
      if (lookahead == 'a') ADVANCE(97);
      if (lookahead == 'l') ADVANCE(98);
      if (lookahead == 's') ADVANCE(99);
      END_STATE();
    case 75:
      if (lookahead == 'i') ADVANCE(100);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_name);
      END_STATE();
    case 77:
      if (lookahead == 'g') ADVANCE(101);
      END_STATE();
    case 78:
      if (lookahead == 'p') ADVANCE(102);
      END_STATE();
    case 79:
      if (lookahead == 'x') ADVANCE(103);
      END_STATE();
    case 80:
      if (lookahead == 'i') ADVANCE(104);
      END_STATE();
    case 81:
      if (lookahead == 'c') ADVANCE(105);
      END_STATE();
    case 82:
      if (lookahead == 'n') ADVANCE(106);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 85:
      if (lookahead == 'd') ADVANCE(107);
      END_STATE();
    case 86:
      if (lookahead == 'i') ADVANCE(108);
      END_STATE();
    case 87:
      if (lookahead == 'r') ADVANCE(109);
      END_STATE();
    case 88:
      if (lookahead == 'r') ADVANCE(110);
      END_STATE();
    case 89:
      if (lookahead == 'e') ADVANCE(111);
      END_STATE();
    case 90:
      if (lookahead == 'i') ADVANCE(112);
      END_STATE();
    case 91:
      if (lookahead == 'l') ADVANCE(113);
      END_STATE();
    case 92:
      if (lookahead == 'd') ADVANCE(114);
      END_STATE();
    case 93:
      if (lookahead == 'i') ADVANCE(115);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 95:
      if (lookahead == 'e') ADVANCE(116);
      END_STATE();
    case 96:
      if (lookahead == 'e') ADVANCE(117);
      END_STATE();
    case 97:
      if (lookahead == 'c') ADVANCE(118);
      END_STATE();
    case 98:
      if (lookahead == 'e') ADVANCE(119);
      END_STATE();
    case 99:
      if (lookahead == 'e') ADVANCE(120);
      END_STATE();
    case 100:
      if (lookahead == 's') ADVANCE(121);
      END_STATE();
    case 101:
      if (lookahead == 'r') ADVANCE(122);
      END_STATE();
    case 102:
      if (lookahead == 't') ADVANCE(123);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_regex);
      END_STATE();
    case 104:
      if (lookahead == 'r') ADVANCE(124);
      END_STATE();
    case 105:
      if (lookahead == 't') ADVANCE(125);
      END_STATE();
    case 106:
      if (lookahead == 'g') ADVANCE(126);
      END_STATE();
    case 107:
      if (lookahead == 'a') ADVANCE(127);
      END_STATE();
    case 108:
      if (lookahead == 'o') ADVANCE(128);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_author);
      END_STATE();
    case 110:
      if (lookahead == 'i') ADVANCE(129);
      END_STATE();
    case 111:
      if (lookahead == 's') ADVANCE(130);
      END_STATE();
    case 112:
      if (lookahead == 'n') ADVANCE(131);
      END_STATE();
    case 113:
      if (lookahead == 't') ADVANCE(132);
      END_STATE();
    case 114:
      if (lookahead == 's') ADVANCE(133);
      END_STATE();
    case 115:
      if (lookahead == 'p') ADVANCE(134);
      END_STATE();
    case 116:
      if (lookahead == 'n') ADVANCE(135);
      END_STATE();
    case 117:
      if (lookahead == 'l') ADVANCE(136);
      END_STATE();
    case 118:
      if (lookahead == 'h') ADVANCE(137);
      END_STATE();
    case 119:
      if (lookahead == 'n') ADVANCE(138);
      END_STATE();
    case 120:
      if (lookahead == 'l') ADVANCE(139);
      END_STATE();
    case 121:
      if (lookahead == 'e') ADVANCE(140);
      END_STATE();
    case 122:
      if (lookahead == 'a') ADVANCE(141);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_prompt);
      END_STATE();
    case 124:
      if (lookahead == 'e') ADVANCE(142);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_select);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 127:
      if (lookahead == 't') ADVANCE(143);
      END_STATE();
    case 128:
      if (lookahead == 'n') ADVANCE(144);
      END_STATE();
    case 129:
      if (lookahead == 'n') ADVANCE(145);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_choices);
      END_STATE();
    case 131:
      if (lookahead == 's') ADVANCE(146);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_default);
      END_STATE();
    case 133:
      if (lookahead == '_') ADVANCE(147);
      END_STATE();
    case 134:
      if (lookahead == 't') ADVANCE(148);
      END_STATE();
    case 135:
      if (lookahead == 'g') ADVANCE(149);
      END_STATE();
    case 136:
      if (lookahead == 'e') ADVANCE(150);
      END_STATE();
    case 137:
      if (lookahead == 'i') ADVANCE(151);
      END_STATE();
    case 138:
      if (lookahead == 'g') ADVANCE(152);
      END_STATE();
    case 139:
      if (lookahead == 'e') ADVANCE(153);
      END_STATE();
    case 140:
      if (lookahead == 'l') ADVANCE(154);
      END_STATE();
    case 141:
      if (lookahead == 'p') ADVANCE(155);
      END_STATE();
    case 142:
      if (lookahead == 'd') ADVANCE(156);
      END_STATE();
    case 143:
      if (lookahead == 'e') ADVANCE(157);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_version);
      END_STATE();
    case 145:
      if (lookahead == 't') ADVANCE(158);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_method_name);
      END_STATE();
    case 147:
      if (lookahead == 'o') ADVANCE(159);
      END_STATE();
    case 148:
      if (lookahead == 'i') ADVANCE(160);
      END_STATE();
    case 149:
      if (lookahead == 't') ADVANCE(161);
      END_STATE();
    case 150:
      if (lookahead == 'c') ADVANCE(162);
      END_STATE();
    case 151:
      if (lookahead == 't') ADVANCE(163);
      END_STATE();
    case 152:
      if (lookahead == 't') ADVANCE(164);
      END_STATE();
    case 153:
      if (lookahead == 'c') ADVANCE(165);
      END_STATE();
    case 154:
      if (lookahead == 'e') ADVANCE(166);
      END_STATE();
    case 155:
      if (lookahead == 'h') ADVANCE(167);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(anon_sym_required);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(anon_sym_validate);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(anon_sym_blueprint);
      END_STATE();
    case 159:
      if (lookahead == 'n') ADVANCE(168);
      END_STATE();
    case 160:
      if (lookahead == 'o') ADVANCE(169);
      END_STATE();
    case 161:
      if (lookahead == 'h') ADVANCE(170);
      END_STATE();
    case 162:
      if (lookahead == 't') ADVANCE(171);
      END_STATE();
    case 163:
      if (lookahead == 'e') ADVANCE(172);
      END_STATE();
    case 164:
      if (lookahead == 'h') ADVANCE(173);
      END_STATE();
    case 165:
      if (lookahead == 't') ADVANCE(174);
      END_STATE();
    case 166:
      if (lookahead == 'c') ADVANCE(175);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(anon_sym_paragraph);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(anon_sym_depends_on);
      END_STATE();
    case 169:
      if (lookahead == 'n') ADVANCE(176);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(anon_sym_max_length);
      END_STATE();
    case 171:
      if (lookahead == 'i') ADVANCE(177);
      END_STATE();
    case 172:
      if (lookahead == 'k') ADVANCE(178);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(anon_sym_min_length);
      END_STATE();
    case 174:
      if (lookahead == 'i') ADVANCE(179);
      END_STATE();
    case 175:
      if (lookahead == 't') ADVANCE(180);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(anon_sym_description);
      END_STATE();
    case 177:
      if (lookahead == 'o') ADVANCE(181);
      END_STATE();
    case 178:
      if (lookahead == '_') ADVANCE(182);
      END_STATE();
    case 179:
      if (lookahead == 'o') ADVANCE(183);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(anon_sym_multiselect);
      END_STATE();
    case 181:
      if (lookahead == 'n') ADVANCE(184);
      END_STATE();
    case 182:
      if (lookahead == 'v') ADVANCE(185);
      END_STATE();
    case 183:
      if (lookahead == 'n') ADVANCE(186);
      END_STATE();
    case 184:
      if (lookahead == 's') ADVANCE(187);
      END_STATE();
    case 185:
      if (lookahead == 'e') ADVANCE(188);
      END_STATE();
    case 186:
      if (lookahead == 's') ADVANCE(189);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(anon_sym_max_selections);
      END_STATE();
    case 188:
      if (lookahead == 'r') ADVANCE(190);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(anon_sym_min_selections);
      END_STATE();
    case 190:
      if (lookahead == 's') ADVANCE(191);
      END_STATE();
    case 191:
      if (lookahead == 'i') ADVANCE(192);
      END_STATE();
    case 192:
      if (lookahead == 'o') ADVANCE(193);
      END_STATE();
    case 193:
      if (lookahead == 'n') ADVANCE(194);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(anon_sym_min_achitek_version);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 4},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 4},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 4},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 4},
  [91] = {.lex_state = 4},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 4},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 4},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 4},
  [101] = {.lex_state = 4},
  [102] = {.lex_state = 4},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_blueprint] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_version] = ACTIONS(1),
    [anon_sym_name] = ACTIONS(1),
    [anon_sym_description] = ACTIONS(1),
    [anon_sym_author] = ACTIONS(1),
    [anon_sym_min_achitek_version] = ACTIONS(1),
    [anon_sym_prompt] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_help] = ACTIONS(1),
    [anon_sym_choices] = ACTIONS(1),
    [anon_sym_default] = ACTIONS(1),
    [anon_sym_required] = ACTIONS(1),
    [anon_sym_depends_on] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_paragraph] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_select] = ACTIONS(1),
    [anon_sym_multiselect] = ACTIONS(1),
    [anon_sym_validate] = ACTIONS(1),
    [anon_sym_regex] = ACTIONS(1),
    [anon_sym_min_length] = ACTIONS(1),
    [anon_sym_max_length] = ACTIONS(1),
    [anon_sym_min_selections] = ACTIONS(1),
    [anon_sym_max_selections] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_method_name] = ACTIONS(1),
    [anon_sym_all] = ACTIONS(1),
    [anon_sym_any] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_file] = STATE(92),
    [sym_blueprint_block] = STATE(55),
    [anon_sym_blueprint] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_version,
      anon_sym_name,
      anon_sym_description,
      anon_sym_author,
      anon_sym_min_achitek_version,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_regex,
      anon_sym_min_length,
      anon_sym_max_length,
      anon_sym_min_selections,
      anon_sym_max_selections,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [28] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_version,
      anon_sym_name,
      anon_sym_description,
      anon_sym_author,
      anon_sym_min_achitek_version,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_regex,
      anon_sym_min_length,
      anon_sym_max_length,
      anon_sym_min_selections,
      anon_sym_max_selections,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [56] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 1,
      anon_sym_type,
    ACTIONS(15), 1,
      anon_sym_help,
    ACTIONS(17), 1,
      anon_sym_choices,
    ACTIONS(19), 1,
      anon_sym_default,
    ACTIONS(21), 1,
      anon_sym_required,
    ACTIONS(23), 1,
      anon_sym_depends_on,
    ACTIONS(25), 1,
      anon_sym_validate,
    STATE(5), 3,
      sym_question_attribute,
      sym_validate_block,
      aux_sym_prompt_block_repeat1,
    STATE(35), 6,
      sym_type_attribute,
      sym_help_attribute,
      sym_choices_attribute,
      sym_default_attribute,
      sym_required_attribute,
      sym_depends_on_attribute,
  [97] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 1,
      anon_sym_type,
    ACTIONS(32), 1,
      anon_sym_help,
    ACTIONS(35), 1,
      anon_sym_choices,
    ACTIONS(38), 1,
      anon_sym_default,
    ACTIONS(41), 1,
      anon_sym_required,
    ACTIONS(44), 1,
      anon_sym_depends_on,
    ACTIONS(47), 1,
      anon_sym_validate,
    STATE(5), 3,
      sym_question_attribute,
      sym_validate_block,
      aux_sym_prompt_block_repeat1,
    STATE(35), 6,
      sym_type_attribute,
      sym_help_attribute,
      sym_choices_attribute,
      sym_default_attribute,
      sym_required_attribute,
      sym_depends_on_attribute,
  [138] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_type,
    ACTIONS(15), 1,
      anon_sym_help,
    ACTIONS(17), 1,
      anon_sym_choices,
    ACTIONS(19), 1,
      anon_sym_default,
    ACTIONS(21), 1,
      anon_sym_required,
    ACTIONS(23), 1,
      anon_sym_depends_on,
    ACTIONS(25), 1,
      anon_sym_validate,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    STATE(4), 3,
      sym_question_attribute,
      sym_validate_block,
      aux_sym_prompt_block_repeat1,
    STATE(35), 6,
      sym_type_attribute,
      sym_help_attribute,
      sym_choices_attribute,
      sym_default_attribute,
      sym_required_attribute,
      sym_depends_on_attribute,
  [179] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    ACTIONS(54), 1,
      anon_sym_regex,
    ACTIONS(56), 1,
      anon_sym_min_length,
    ACTIONS(58), 1,
      anon_sym_max_length,
    ACTIONS(60), 1,
      anon_sym_min_selections,
    ACTIONS(62), 1,
      anon_sym_max_selections,
    STATE(10), 2,
      sym_validate_attribute,
      aux_sym_validate_block_repeat1,
    STATE(48), 5,
      sym_regex_attribute,
      sym_min_length_attribute,
      sym_max_length_attribute,
      sym_min_selections_attribute,
      sym_max_selections_attribute,
  [212] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_DOT,
    ACTIONS(66), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(64), 10,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [235] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    ACTIONS(72), 1,
      anon_sym_regex,
    ACTIONS(75), 1,
      anon_sym_min_length,
    ACTIONS(78), 1,
      anon_sym_max_length,
    ACTIONS(81), 1,
      anon_sym_min_selections,
    ACTIONS(84), 1,
      anon_sym_max_selections,
    STATE(9), 2,
      sym_validate_attribute,
      aux_sym_validate_block_repeat1,
    STATE(48), 5,
      sym_regex_attribute,
      sym_min_length_attribute,
      sym_max_length_attribute,
      sym_min_selections_attribute,
      sym_max_selections_attribute,
  [268] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_regex,
    ACTIONS(56), 1,
      anon_sym_min_length,
    ACTIONS(58), 1,
      anon_sym_max_length,
    ACTIONS(60), 1,
      anon_sym_min_selections,
    ACTIONS(62), 1,
      anon_sym_max_selections,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_validate_attribute,
      aux_sym_validate_block_repeat1,
    STATE(48), 5,
      sym_regex_attribute,
      sym_min_length_attribute,
      sym_max_length_attribute,
      sym_min_selections_attribute,
      sym_max_selections_attribute,
  [301] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(93), 1,
      anon_sym_RBRACK,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    ACTIONS(97), 1,
      sym_integer,
    STATE(59), 1,
      sym_value,
    STATE(86), 1,
      sym_value_list,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 3,
      sym_array,
      sym_string_literal,
      sym_boolean,
  [335] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 11,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [352] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    ACTIONS(97), 1,
      sym_integer,
    ACTIONS(103), 1,
      anon_sym_RBRACK,
    STATE(72), 1,
      sym_value,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 3,
      sym_array,
      sym_string_literal,
      sym_boolean,
  [383] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    ACTIONS(97), 1,
      sym_integer,
    ACTIONS(105), 1,
      anon_sym_RBRACK,
    STATE(72), 1,
      sym_value,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 3,
      sym_array,
      sym_string_literal,
      sym_boolean,
  [414] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 10,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [430] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(64), 1,
      sym_dependency_expr,
    STATE(84), 1,
      sym_combinator_name,
    STATE(85), 1,
      sym_dependency_list,
    ACTIONS(111), 2,
      anon_sym_all,
      anon_sym_any,
    STATE(17), 4,
      sym_simple_dependency,
      sym_comparison_dependency,
      sym_method_call_dependency,
      sym_combinator_dependency,
  [456] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 10,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [472] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    ACTIONS(97), 1,
      sym_integer,
    STATE(36), 1,
      sym_value,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 3,
      sym_array,
      sym_string_literal,
      sym_boolean,
  [500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 10,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [516] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 10,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [532] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 10,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [548] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 10,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [564] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 10,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [580] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym_dependency_expr,
    STATE(84), 1,
      sym_combinator_name,
    ACTIONS(111), 2,
      anon_sym_all,
      anon_sym_any,
    STATE(17), 4,
      sym_simple_dependency,
      sym_comparison_dependency,
      sym_method_call_dependency,
      sym_combinator_dependency,
  [606] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    ACTIONS(97), 1,
      sym_integer,
    STATE(72), 1,
      sym_value,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 3,
      sym_array,
      sym_string_literal,
      sym_boolean,
  [634] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym_dependency_expr,
    STATE(84), 1,
      sym_combinator_name,
    ACTIONS(111), 2,
      anon_sym_all,
      anon_sym_any,
    STATE(17), 4,
      sym_simple_dependency,
      sym_comparison_dependency,
      sym_method_call_dependency,
      sym_combinator_dependency,
  [660] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 10,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [676] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_blueprint_attribute_key,
    STATE(28), 2,
      sym_blueprint_attribute,
      aux_sym_blueprint_block_repeat1,
    ACTIONS(133), 5,
      anon_sym_version,
      anon_sym_name,
      anon_sym_description,
      anon_sym_author,
      anon_sym_min_achitek_version,
  [697] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_blueprint_attribute_key,
    STATE(28), 2,
      sym_blueprint_attribute,
      aux_sym_blueprint_block_repeat1,
    ACTIONS(138), 5,
      anon_sym_version,
      anon_sym_name,
      anon_sym_description,
      anon_sym_author,
      anon_sym_min_achitek_version,
  [718] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(39), 1,
      sym_dependency_expr,
    STATE(84), 1,
      sym_combinator_name,
    ACTIONS(111), 2,
      anon_sym_all,
      anon_sym_any,
    STATE(17), 4,
      sym_simple_dependency,
      sym_comparison_dependency,
      sym_method_call_dependency,
      sym_combinator_dependency,
  [741] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_blueprint_attribute_key,
    STATE(29), 2,
      sym_blueprint_attribute,
      aux_sym_blueprint_block_repeat1,
    ACTIONS(138), 5,
      anon_sym_version,
      anon_sym_name,
      anon_sym_description,
      anon_sym_author,
      anon_sym_min_achitek_version,
  [762] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(76), 1,
      sym_dependency_expr,
    STATE(84), 1,
      sym_combinator_name,
    ACTIONS(111), 2,
      anon_sym_all,
      anon_sym_any,
    STATE(17), 4,
      sym_simple_dependency,
      sym_comparison_dependency,
      sym_method_call_dependency,
      sym_combinator_dependency,
  [785] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 8,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
  [799] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 8,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
  [813] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 8,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
  [827] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 8,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
  [841] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 8,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
  [855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 8,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
  [869] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 8,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
  [883] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 8,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
  [897] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 8,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
  [911] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 8,
      anon_sym_RBRACE,
      anon_sym_type,
      anon_sym_help,
      anon_sym_choices,
      anon_sym_default,
      anon_sym_required,
      anon_sym_depends_on,
      anon_sym_validate,
  [925] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      sym_integer,
    STATE(22), 1,
      sym_literal_value,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_string_literal,
      sym_boolean,
  [946] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    ACTIONS(162), 1,
      sym_integer,
    STATE(99), 1,
      sym_literal_value,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_string_literal,
      sym_boolean,
  [967] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 6,
      anon_sym_RBRACE,
      anon_sym_regex,
      anon_sym_min_length,
      anon_sym_max_length,
      anon_sym_min_selections,
      anon_sym_max_selections,
  [979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 6,
      anon_sym_RBRACE,
      anon_sym_regex,
      anon_sym_min_length,
      anon_sym_max_length,
      anon_sym_min_selections,
      anon_sym_max_selections,
  [991] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 6,
      anon_sym_RBRACE,
      anon_sym_regex,
      anon_sym_min_length,
      anon_sym_max_length,
      anon_sym_min_selections,
      anon_sym_max_selections,
  [1003] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 6,
      anon_sym_RBRACE,
      anon_sym_regex,
      anon_sym_min_length,
      anon_sym_max_length,
      anon_sym_min_selections,
      anon_sym_max_selections,
  [1015] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 6,
      anon_sym_RBRACE,
      anon_sym_version,
      anon_sym_name,
      anon_sym_description,
      anon_sym_author,
      anon_sym_min_achitek_version,
  [1027] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 6,
      anon_sym_RBRACE,
      anon_sym_regex,
      anon_sym_min_length,
      anon_sym_max_length,
      anon_sym_min_selections,
      anon_sym_max_selections,
  [1039] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 6,
      anon_sym_RBRACE,
      anon_sym_regex,
      anon_sym_min_length,
      anon_sym_max_length,
      anon_sym_min_selections,
      anon_sym_max_selections,
  [1051] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(38), 1,
      sym_question_type,
    ACTIONS(180), 5,
      anon_sym_string,
      anon_sym_paragraph,
      anon_sym_bool,
      anon_sym_select,
      anon_sym_multiselect,
  [1065] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      ts_builtin_sym_end,
    ACTIONS(184), 1,
      anon_sym_prompt,
    STATE(56), 2,
      sym_prompt_block,
      aux_sym_file_repeat1,
  [1079] = 4,
    ACTIONS(186), 1,
      anon_sym_DQUOTE,
    ACTIONS(190), 1,
      sym_comment,
    STATE(57), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(188), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1093] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_prompt,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
    STATE(53), 2,
      sym_prompt_block,
      aux_sym_file_repeat1,
  [1107] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
    ACTIONS(196), 1,
      anon_sym_prompt,
    STATE(56), 2,
      sym_prompt_block,
      aux_sym_file_repeat1,
  [1121] = 4,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(201), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1135] = 4,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(205), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1149] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      aux_sym_value_list_repeat1,
  [1162] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    STATE(60), 1,
      aux_sym_dependency_list_repeat1,
  [1175] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(33), 1,
      sym_boolean,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
  [1186] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_RBRACK,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym_value_list_repeat1,
  [1199] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    STATE(60), 1,
      aux_sym_dependency_list_repeat1,
  [1212] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    STATE(63), 1,
      aux_sym_dependency_list_repeat1,
  [1225] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RBRACK,
    STATE(65), 1,
      aux_sym_value_list_repeat1,
  [1238] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    STATE(41), 1,
      sym_array,
  [1248] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      sym_string_literal,
  [1258] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    STATE(45), 1,
      sym_string_literal,
  [1268] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    STATE(49), 1,
      sym_string_literal,
  [1278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 2,
      ts_builtin_sym_end,
      anon_sym_prompt,
  [1286] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 2,
      ts_builtin_sym_end,
      anon_sym_prompt,
  [1294] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1302] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 2,
      ts_builtin_sym_end,
      anon_sym_prompt,
  [1310] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    STATE(77), 1,
      sym_string_literal,
  [1320] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 2,
      ts_builtin_sym_end,
      anon_sym_prompt,
  [1328] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LBRACE,
  [1343] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_EQ,
  [1350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_EQ,
  [1357] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_EQ,
  [1364] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_LBRACE,
  [1371] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_EQ,
  [1378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_LPAREN,
  [1385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_LPAREN,
  [1392] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
  [1399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_RBRACK,
  [1406] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_EQ,
  [1413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_LBRACE,
  [1420] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_method_name,
  [1427] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_EQ,
  [1434] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_EQ,
  [1441] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      ts_builtin_sym_end,
  [1448] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_integer,
  [1455] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      sym_integer,
  [1462] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_EQ,
  [1469] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      sym_integer,
  [1476] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      sym_integer,
  [1483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_EQ,
  [1490] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
  [1497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_EQ,
  [1504] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_EQ,
  [1511] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_EQ,
  [1518] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_LPAREN,
  [1525] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 97,
  [SMALL_STATE(6)] = 138,
  [SMALL_STATE(7)] = 179,
  [SMALL_STATE(8)] = 212,
  [SMALL_STATE(9)] = 235,
  [SMALL_STATE(10)] = 268,
  [SMALL_STATE(11)] = 301,
  [SMALL_STATE(12)] = 335,
  [SMALL_STATE(13)] = 352,
  [SMALL_STATE(14)] = 383,
  [SMALL_STATE(15)] = 414,
  [SMALL_STATE(16)] = 430,
  [SMALL_STATE(17)] = 456,
  [SMALL_STATE(18)] = 472,
  [SMALL_STATE(19)] = 500,
  [SMALL_STATE(20)] = 516,
  [SMALL_STATE(21)] = 532,
  [SMALL_STATE(22)] = 548,
  [SMALL_STATE(23)] = 564,
  [SMALL_STATE(24)] = 580,
  [SMALL_STATE(25)] = 606,
  [SMALL_STATE(26)] = 634,
  [SMALL_STATE(27)] = 660,
  [SMALL_STATE(28)] = 676,
  [SMALL_STATE(29)] = 697,
  [SMALL_STATE(30)] = 718,
  [SMALL_STATE(31)] = 741,
  [SMALL_STATE(32)] = 762,
  [SMALL_STATE(33)] = 785,
  [SMALL_STATE(34)] = 799,
  [SMALL_STATE(35)] = 813,
  [SMALL_STATE(36)] = 827,
  [SMALL_STATE(37)] = 841,
  [SMALL_STATE(38)] = 855,
  [SMALL_STATE(39)] = 869,
  [SMALL_STATE(40)] = 883,
  [SMALL_STATE(41)] = 897,
  [SMALL_STATE(42)] = 911,
  [SMALL_STATE(43)] = 925,
  [SMALL_STATE(44)] = 946,
  [SMALL_STATE(45)] = 967,
  [SMALL_STATE(46)] = 979,
  [SMALL_STATE(47)] = 991,
  [SMALL_STATE(48)] = 1003,
  [SMALL_STATE(49)] = 1015,
  [SMALL_STATE(50)] = 1027,
  [SMALL_STATE(51)] = 1039,
  [SMALL_STATE(52)] = 1051,
  [SMALL_STATE(53)] = 1065,
  [SMALL_STATE(54)] = 1079,
  [SMALL_STATE(55)] = 1093,
  [SMALL_STATE(56)] = 1107,
  [SMALL_STATE(57)] = 1121,
  [SMALL_STATE(58)] = 1135,
  [SMALL_STATE(59)] = 1149,
  [SMALL_STATE(60)] = 1162,
  [SMALL_STATE(61)] = 1175,
  [SMALL_STATE(62)] = 1186,
  [SMALL_STATE(63)] = 1199,
  [SMALL_STATE(64)] = 1212,
  [SMALL_STATE(65)] = 1225,
  [SMALL_STATE(66)] = 1238,
  [SMALL_STATE(67)] = 1248,
  [SMALL_STATE(68)] = 1258,
  [SMALL_STATE(69)] = 1268,
  [SMALL_STATE(70)] = 1278,
  [SMALL_STATE(71)] = 1286,
  [SMALL_STATE(72)] = 1294,
  [SMALL_STATE(73)] = 1302,
  [SMALL_STATE(74)] = 1310,
  [SMALL_STATE(75)] = 1320,
  [SMALL_STATE(76)] = 1328,
  [SMALL_STATE(77)] = 1336,
  [SMALL_STATE(78)] = 1343,
  [SMALL_STATE(79)] = 1350,
  [SMALL_STATE(80)] = 1357,
  [SMALL_STATE(81)] = 1364,
  [SMALL_STATE(82)] = 1371,
  [SMALL_STATE(83)] = 1378,
  [SMALL_STATE(84)] = 1385,
  [SMALL_STATE(85)] = 1392,
  [SMALL_STATE(86)] = 1399,
  [SMALL_STATE(87)] = 1406,
  [SMALL_STATE(88)] = 1413,
  [SMALL_STATE(89)] = 1420,
  [SMALL_STATE(90)] = 1427,
  [SMALL_STATE(91)] = 1434,
  [SMALL_STATE(92)] = 1441,
  [SMALL_STATE(93)] = 1448,
  [SMALL_STATE(94)] = 1455,
  [SMALL_STATE(95)] = 1462,
  [SMALL_STATE(96)] = 1469,
  [SMALL_STATE(97)] = 1476,
  [SMALL_STATE(98)] = 1483,
  [SMALL_STATE(99)] = 1490,
  [SMALL_STATE(100)] = 1497,
  [SMALL_STATE(101)] = 1504,
  [SMALL_STATE(102)] = 1511,
  [SMALL_STATE(103)] = 1518,
  [SMALL_STATE(104)] = 1525,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_prompt_block_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prompt_block_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prompt_block_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prompt_block_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prompt_block_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prompt_block_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prompt_block_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prompt_block_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_dependency, 1, 0, 4),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_validate_block_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_validate_block_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_validate_block_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_validate_block_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_validate_block_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_validate_block_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_list, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_list, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_combinator_dependency, 4, 0, 6),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_expr, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_value, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_dependency, 3, 0, 5),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_list, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_list, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call_dependency, 6, 0, 7),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_blueprint_block_repeat1, 2, 0, 0),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_blueprint_block_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_required_attribute, 3, 0, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_validate_block, 4, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_question_attribute, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_attribute, 3, 0, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_question_type, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_attribute, 3, 0, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depends_on_attribute, 3, 0, 3),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_help_attribute, 3, 0, 3),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choices_attribute, 3, 0, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_validate_block, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regex_attribute, 3, 0, 3),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_min_length_attribute, 3, 0, 3),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_max_length_attribute, 3, 0, 3),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_validate_attribute, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blueprint_attribute, 3, 0, 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_max_selections_attribute, 3, 0, 3),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_min_selections_attribute, 3, 0, 3),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value_list, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dependency_list_repeat1, 2, 0, 0),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dependency_list_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_list, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_list_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_list_repeat1, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prompt_block, 5, 0, 2),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blueprint_block, 4, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blueprint_block, 3, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prompt_block, 4, 0, 2),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [268] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blueprint_attribute_key, 1, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_combinator_name, 1, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_achitekfile(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "achitekfile",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
